import type { StoredCookie } from './types';

export function normalizeCookie(cookie: Browser.cookies.Cookie): StoredCookie {
  return {
    name: cookie.name,
    value: cookie.value,
    domain: cookie.domain,
    path: cookie.path,
    secure: cookie.secure,
    httpOnly: cookie.httpOnly,
    sameSite: cookie.sameSite,
    expirationDate: cookie.expirationDate,
  };
}

export function formatCookiesForExport(cookies: Record<string, StoredCookie[]>): string {
  return Object.entries(cookies)
    .map(([domain, domainCookies]) => {
      const cookieLines = domainCookies
        .map((cookie) => `${cookie.name}=${cookie.value}; domain=${cookie.domain}; path=${cookie.path}`)
        .join('\n');
      return `# ${domain}\n${cookieLines}`;
    })
    .join('\n\n');
}

function sanitizeCookieField(value: string | number | boolean | undefined): string {
  return String(value ?? '').replace(/[\t\r\n]/g, ' ');
}

export function formatCookiesAsNetscape(cookies: Record<string, StoredCookie[]>): string {
  const lines = [
    '# Netscape HTTP Cookie File',
    '# https://curl.se/docs/http-cookies.html',
    '# This file was generated by ArchiveBox Browser Extension',
    '#',
    '# Format: domain\\tincludeSubdomains\\tpath\\tsecure\\texpiry\\tname\\tvalue',
    '',
  ];

  for (const domainCookies of Object.values(cookies)) {
    for (const cookie of domainCookies) {
      const domain = sanitizeCookieField(cookie.domain);
      const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
      const path = sanitizeCookieField(cookie.path || '/');
      const secure = cookie.secure ? 'TRUE' : 'FALSE';
      const expiry = cookie.expirationDate && cookie.expirationDate > 0
        ? String(Math.floor(cookie.expirationDate))
        : '0';
      lines.push([
        domain,
        includeSubdomains,
        path,
        secure,
        expiry,
        sanitizeCookieField(cookie.name),
        sanitizeCookieField(cookie.value),
      ].join('\t'));
    }
  }

  return `${lines.join('\n')}\n`;
}

export async function getCookiesByDomain(): Promise<Record<string, StoredCookie[]>> {
  const allCookies = await browser.cookies.getAll({});
  return allCookies.reduce<Record<string, StoredCookie[]>>((acc, cookie) => {
    const domain = cookie.domain.startsWith('.') ? cookie.domain.slice(1) : cookie.domain;
    acc[domain] ||= [];
    acc[domain].push(normalizeCookie(cookie));
    return acc;
  }, {});
}
