import React from 'react';
import type {ArchiveReader,ArchiveEntry,ArchivedExchange} from '../archive/reader';
import {mountReplay,recordURL,replayHTML} from '../archive/replay';
import {explainRecordedHeaders,describeRecordedHeaders} from '../capture/request-match';
import './responses.css';
const http=(entry:ArchiveEntry)=>/^https?:/i.test(entry.url);
const type=(mime:string)=>mime.includes('json')?'JSON':mime.includes('javascript')?'JS':mime.includes('css')?'CSS':mime.includes('html')?'HTML':mime.startsWith('image/')?'Image':mime.startsWith('font/')||mime.includes('woff')?'Font':mime.startsWith('video/')||mime.startsWith('audio/')?'Media':mime.includes('pdf')?'PDF':'Other';
const bytes=(n:number)=>n>=1048576?(n/1048576).toFixed(1)+' MB':n>=1024?(n/1024).toFixed(1)+' kB':n+' B';
const identity=(entry:ArchiveEntry)=>entry.url+'@'+entry.ts;
const interval=(timing:any,start:string,end:string)=>typeof timing?.[start]==='number'&&timing[start]>=0&&timing[end]>=timing[start]?timing[end]-timing[start]:null;
const milliseconds=(n:number|null)=>n===null?'—':n.toFixed(1)+' ms';
function HeadersTable({headers}:{headers:Record<string,string>|null}){return headers===null?<p className="response-empty">Request headers unavailable</p>:<dl className="response-headers">{Object.entries(headers).map(([name,value])=><React.Fragment key={name}><dt>{name}</dt><dd>{value}</dd></React.Fragment>)}</dl>}
function BodyPreview({archive,entry,exchange,preview}:{archive:ArchiveReader;entry:ArchiveEntry;exchange:ArchivedExchange;preview:boolean}){
 const [text,setText]=React.useState<string>(),[html,setHTML]=React.useState(''),[error,setError]=React.useState('');
 const mime=new Headers(exchange.responseHeaders).get('content-type')||entry.mime;
 React.useEffect(()=>{let current=true;setText(undefined);setHTML('');setError('');void(async()=>{
  await mountReplay(archive);
  if(/text|json|xml|javascript/.test(mime)||!preview){const record=await archive.read(entry);const value=/text|json|xml|javascript/.test(mime)?new TextDecoder().decode(record.body):Array.from(record.body.slice(0,65536),(b,i)=>(i%16===0?`${i.toString(16).padStart(8,'0')}  `:'')+b.toString(16).padStart(2,'0')+(i%16===15?'\n':' ')).join('')+(record.body.length>65536?`\n… First 65,536 of ${record.body.length.toLocaleString()} bytes`:'');if(current)setText(value);
   if(preview&&mime.includes('html')){const prepared=await replayHTML(archive,value,exchange.url);if(current)setHTML(prepared);}
  }
 })().catch(e=>{if(current)setError(String(e))});return()=>{current=false};},[archive,entry,mime,preview,exchange.url]);
 if(error)return <p role="alert">{error}</p>;
 if(preview&&mime.includes('html'))return <iframe title="Response preview" sandbox="allow-same-origin" srcDoc={html}/>;
 if(preview&&mime.startsWith('image/'))return <img alt="Response preview" src={recordURL(archive,entry)}/>;
 if(preview&&mime.startsWith('audio/'))return <audio controls src={recordURL(archive,entry)}/>;
 if(preview&&mime.startsWith('video/'))return <video controls src={recordURL(archive,entry)}/>;
 if(preview&&mime.includes('pdf'))return <iframe title="Response preview" src={recordURL(archive,entry)}/>;
 if(preview&&text===undefined&&!/text|json|xml|javascript/.test(mime))return <p>{mime}</p>;
 let rendered=text;if(preview&&mime.includes('json')&&text){try{rendered=JSON.stringify(JSON.parse(text),null,2)}catch{}}
 return <pre>{rendered??'Loading…'}</pre>;
}
export function ResponsesPreview({archive}:{archive:ArchiveReader}){
 const entries=React.useMemo(()=>archive.entries.filter(http).sort((a,b)=>a.ts-b.ts),[archive]);
 const initial=()=>{const params=new URLSearchParams(location.hash.slice(1));return entries.find(entry=>entry.url===params.get('request')&&entry.ts===Number(params.get('ts')))||entries[0]};
 const [selected,setSelected]=React.useState<ArchiveEntry|undefined>(initial),[query,setQuery]=React.useState(''),[kind,setKind]=React.useState('All'),[status,setStatus]=React.useState('All'),[method,setMethod]=React.useState('All'),[tab,setTab]=React.useState('Headers'),[exchange,setExchange]=React.useState<ArchivedExchange>(),[error,setError]=React.useState('');
 const [metadata,setMetadata]=React.useState<Record<string,any>>({}),[comparison,setComparison]=React.useState(''),[compared,setCompared]=React.useState<ArchivedExchange>();
 React.useEffect(()=>{const listener=()=>{const params=new URLSearchParams(location.hash.slice(1));const entry=entries.find(item=>item.url===params.get('request')&&item.ts===Number(params.get('ts')));if(entry)setSelected(entry)};addEventListener('hashchange',listener);return()=>removeEventListener('hashchange',listener)},[entries]);
 React.useEffect(()=>{let current=true;let cursor=0;void Promise.all(Array.from({length:4},async()=>{while(current&&cursor<entries.length){const entry=entries[cursor++]!;try{const record=await archive.headers(entry);const data=JSON.parse(record.warcHeaders['WARC-JSON-Metadata']||'{}');if(current)setMetadata(old=>({...old,[identity(entry)]:{...data,originalUrl:record.url,contentType:record.headers['content-type']?.split(';')[0]||entry.mime}}));}catch{}}}));return()=>{current=false};},[archive,entries]);
 React.useEffect(()=>{let current=true;setExchange(undefined);setError('');setComparison('');setCompared(undefined);if(selected)void archive.exchange(selected).then(value=>{if(current)setExchange(value)}).catch(e=>{if(current)setError(String(e))});return()=>{current=false};},[archive,selected]);
 React.useEffect(()=>{let current=true;setCompared(undefined);const entry=entries.find(item=>identity(item)===comparison);if(entry)void archive.exchange(entry).then(value=>{if(current)setCompared(value)}).catch(e=>{if(current)setError(String(e))});return()=>{current=false};},[archive,entries,comparison]);
 const entryURL=(entry:ArchiveEntry)=>metadata[identity(entry)]?.originalUrl||entry.url;
 const entryMime=(entry:ArchiveEntry)=>metadata[identity(entry)]?.contentType||entry.mime;
 const filtered=entries.filter(entry=>[entryURL(entry),entryMime(entry),entry.status,entry.method].join(' ').toLowerCase().includes(query.toLowerCase())&&(kind==='All'||type(entryMime(entry))===kind)&&(method==='All'||(entry.method||'GET')===method)&&(status==='All'||Math.floor(entry.status/100)===Number(status)));
 const select=(entry:ArchiveEntry)=>{setSelected(entry);const params=new URLSearchParams(location.hash.slice(1));params.set('view','responses');params.set('request',entry.url);params.set('ts',String(entry.ts));history.replaceState(null,'','#'+params.toString())};
 const download=async()=>{if(!selected)return;try{const record=await archive.read(selected);const url=URL.createObjectURL(new Blob([record.body as BlobPart],{type:new Headers(record.headers).get('content-type')||selected.mime}));const link=document.createElement('a');link.href=url;link.download=new URL(exchange?.url||selected.url).pathname.split('/').at(-1)||'response';link.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}catch(e){setError(String(e))}};
 const matchTable=(requested:Record<string,string>,recorded:Record<string,string>,response:Record<string,string>)=>{const result=explainRecordedHeaders(new Headers(requested),new Headers(recorded),new Headers(response));return <><strong className={result.matches?'response-match':'response-mismatch'}>{result.matches?'Headers match':'Headers differ'}</strong><table className="response-match-table"><thead><tr><th>Header</th><th>Requested</th><th>Recorded</th><th>Result</th><th>Rule</th></tr></thead><tbody>{result.headers.map(row=><tr key={row.name}><th>{row.name}</th><td>{row.requested??'—'}</td><td>{row.recorded??'—'}</td><td data-result={row.result}>{row.result}</td><td>{row.reason}</td></tr>)}</tbody></table></>};
 return <div className="responses-inspector"><header><h2>Responses</h2><span>{filtered.length} / {entries.length}</span><input type="search" aria-label="Search requests" placeholder="Filter URL, MIME, method, status" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Resource type" value={kind} onChange={e=>setKind(e.target.value)}>{['All',...new Set(entries.map(entry=>type(entryMime(entry))))].map(value=><option key={value}>{value}</option>)}</select><select aria-label="HTTP method" value={method} onChange={e=>setMethod(e.target.value)}>{['All',...new Set(entries.map(entry=>entry.method||'GET'))].map(value=><option key={value}>{value}</option>)}</select><select aria-label="HTTP status" value={status} onChange={e=>setStatus(e.target.value)}><option>All</option>{[2,3,4,5].map(n=><option value={n} key={n}>{n}xx</option>)}</select></header>
 <div className="responses-panels"><div className="response-list"><table aria-label="Archived requests"><thead><tr><th>Method</th><th>Status</th><th>URL</th><th>Type</th><th>WARC bytes</th><th>TTFB</th></tr></thead><tbody>{filtered.map(entry=><tr key={identity(entry)} aria-selected={entry===selected} onClick={()=>select(entry)}><td>{entry.method||'GET'}</td><td data-status={Math.floor(entry.status/100)}>{entry.status}</td><td><button title={entryURL(entry)} onClick={()=>select(entry)}>{entryURL(entry)}</button></td><td>{type(entryMime(entry))}</td><td>{bytes(entry.length)}</td><td>{milliseconds(interval(metadata[identity(entry)]?.network?.timing,'sendEnd','receiveHeadersEnd'))}</td></tr>)}</tbody></table>{!filtered.length&&<p className="response-empty">No matching requests</p>}</div>
 <section className="response-detail" aria-label="Selected request">{selected&&<><div className="response-selected"><strong>{exchange?.method||selected.method||'GET'}</strong><code>{exchange?.url||selected.url}</code><button onClick={()=>void download()}>Download</button></div><nav aria-label="Request details">{['Headers','Preview','Response','Request','Timing','Header matches'].map(name=><button key={name} aria-pressed={tab===name} onClick={()=>setTab(name)}>{name}</button>)}</nav>{error?<p role="alert">{error}</p>:!exchange?<p>Loading…</p>:<div className="response-content">
 {tab==='Headers'&&<><h3>General</h3><dl className="response-headers"><dt>Status</dt><dd>{exchange.statusLine}</dd><dt>Captured</dt><dd>{new Date(selected.ts).toISOString()}</dd><dt>Content type</dt><dd>{new Headers(exchange.responseHeaders).get('content-type')||selected.mime}</dd><dt>Stored record</dt><dd>{bytes(selected.length)}</dd></dl><h3>Response headers</h3><HeadersTable headers={exchange.responseHeaders}/><h3>Request headers</h3><HeadersTable headers={exchange.requestHeaders}/></>}
 {(tab==='Preview'||tab==='Response')&&<BodyPreview archive={archive} entry={selected} exchange={exchange} preview={tab==='Preview'}/>}
 {tab==='Request'&&<pre>{exchange.requestBody===null?'Request body unavailable':exchange.requestBody.length?new TextDecoder().decode(exchange.requestBody):'Empty request body'}</pre>}
 {tab==='Timing'&&<><dl className="response-headers">{[['Protocol',exchange.metadata.network?.protocol],['Remote address',exchange.metadata.network?.remoteIPAddress],['Connection reused',exchange.metadata.network?.connectionReused]].map(([name,value])=><React.Fragment key={String(name)}><dt>{name}</dt><dd>{value===undefined?'—':String(value)}</dd></React.Fragment>)}</dl><table><tbody>{[['DNS','dnsStart','dnsEnd'],['Connection','connectStart','connectEnd'],['TLS','sslStart','sslEnd'],['Send','sendStart','sendEnd'],['Waiting (TTFB)','sendEnd','receiveHeadersEnd']].map(([name,start,end])=><tr key={name}><th>{name}</th><td>{milliseconds(interval(exchange.metadata.network?.timing,start!,end!))}</td></tr>)}</tbody></table></>}
 {tab==='Header matches'&&<><h3>Incoming header rules</h3>{exchange.requestHeaders?<><table className="response-match-table" aria-label="Header matching rules"><thead><tr><th>Header</th><th>Recorded value</th><th>Used for matching</th><th>Incoming request</th></tr></thead><tbody>{describeRecordedHeaders(new Headers(exchange.requestHeaders),new Headers(exchange.responseHeaders)).map(row=><tr key={row.name}><th>{row.name}</th><td>{row.value??'—'}</td><td>{row.role}</td><td>{row.rule}</td></tr>)}</tbody></table><p className="response-empty">Headers omitted by the incoming request are not compared. An incoming If-* header requires a new response.</p></>:<p>Request headers unavailable</p>}<details><summary>Compare archived request headers</summary><select aria-label="Compare request" value={comparison} onChange={e=>setComparison(e.target.value)}><option value="">Select request</option>{entries.map(entry=><option key={identity(entry)} value={identity(entry)}>{entry.method||'GET'} {entryURL(entry)} · {new Date(entry.ts).toISOString()}</option>)}</select>{compared&&<>{compared.requestHeaders&&exchange.requestHeaders?matchTable(compared.requestHeaders,exchange.requestHeaders,exchange.responseHeaders):<p>Request headers unavailable</p>}</>}</details></>}

 </div>}</>}</section></div></div>;
}
