import type {CanonicalOptions} from '@/src/archive/views';
export type ScrollFrame={timestamp:number;elapsedMs:number;x:number;y:number;width:number;height:number;viewportWidth:number;viewportHeight:number;phase:string;step?:number;expanded?:number;bottom?:boolean;image?:string;source?:string};
export type ScrollEvidence={steps:number;expanded:number;initialHeight:number;finalHeight:number;elapsedMs:number;stopped:boolean;frames?:ScrollFrame[]};
export type ScrollImage={url:string;width:number;height:number;x:number;y:number;fullWidth:number;fullHeight:number;capturedAt:number};
export function renderScroll(document:Document,evidence:ScrollEvidence|null,frames:ScrollFrame[],screenshots:ScrollImage[],source:string,options:CanonicalOptions){
 const el=(tag:string,text?:unknown,cls?:string)=>{const node=document.createElement(tag);if(text!=null)node.textContent=String(text);if(cls)node.className=cls;return node};
 const content=document.getElementById('content')!;if(!evidence){content.append(el('p','No scroll activity recorded','empty'));return}
 const num=(n:number)=>Number(n.toFixed(2)).toLocaleString(),px=(n:number)=>num(n)+' px';
 const first=evidence.frames?.find(frame=>frame.phase==='Initial')||frames[0],last=evidence.frames?.findLast(frame=>frame.phase==='Final')||frames.at(-1),stats=el('section',undefined,'panel metrics');
 const metric=(title:string,value:string,detail?:string)=>{const node=el('div',undefined,'metric');node.append(el('span',title),el('strong',value));if(detail)node.append(el('small',detail));stats.append(node)};
 metric('Initial height',px(evidence.initialHeight),first?.viewportHeight?`${num(evidence.initialHeight/first.viewportHeight)} screens · ${Math.ceil(evidence.initialHeight/first.viewportHeight)} pages`:undefined);
 metric('Final height',px(evidence.finalHeight),last?.viewportHeight?`${num(evidence.finalHeight/last.viewportHeight)} screens · ${Math.ceil(evidence.finalHeight/last.viewportHeight)} pages`:undefined);
 metric('Scroll steps',num(evidence.steps),`${frames.length} recorded positions`);metric('Page growth',`${evidence.finalHeight>=evidence.initialHeight?'+':''}${px(evidence.finalHeight-evidence.initialHeight)}`);metric('Details expanded',num(evidence.expanded));metric('Elapsed',num(evidence.elapsedMs/1000)+' s',evidence.stopped?'Stopped':undefined);content.append(stats);
 const shell=el('section',undefined,'panel browser'),top=el('div',undefined,'chrome-top'),tabs=el('div',undefined,'tabs'),lights=el('div',undefined,'lights');for(const color of ['#ff5f57','#febc2e','#28c840']){const dot=el('span',undefined,'light');dot.style.background=color;lights.append(dot)}const tab=el('div',undefined,'tab');let host=source;try{host=new URL(source).host}catch{}tab.append(el('span','↕'),el('span',host,'tab-title'));tabs.append(lights,tab);const toolbar=el('div',undefined,'toolbar');toolbar.append(el('span','‹ › ↻','muted'),el('div',source,'omnibox'));top.append(tabs,toolbar);shell.append(top);
 const workspace=el('div',undefined,'workspace'),map=el('div',undefined,'document-map'),detail=el('aside',undefined,'detail');workspace.append(map,detail);shell.append(workspace);content.append(shell);
 const extent=Math.max(1,evidence.initialHeight,evidence.finalHeight,...frames.map(f=>f.y+f.viewportHeight)),width=Math.max(1,...frames.map(f=>f.width||f.viewportWidth),...screenshots.map(f=>f.fullWidth));
 const plotHeight=Math.max(330,Math.min(740,extent/width*300)),scale=plotHeight/extent,topY=44,docX=100,docW=260;
 const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox',`0 0 560 ${plotHeight+110}`);svg.setAttribute('role','img');svg.setAttribute('aria-label','Scroll positions over document height');map.append(svg);
 const shape=(tag:string,attrs:Record<string,string|number>,text?:string)=>{const node=document.createElementNS(svg.namespaceURI,tag);for(const[key,value]of Object.entries(attrs))node.setAttribute(key,String(value));if(text)node.textContent=text;svg.append(node);return node};
 shape('rect',{x:docX,y:topY,width:docW,height:evidence.finalHeight*scale,rx:5,fill:'#fff',stroke:'#446b97','stroke-width':2,'data-document-height':evidence.finalHeight});
 shape('text',{x:docX,y:24,fill:'#64748b','font-size':12},'DOCUMENT');
 if(first?.viewportHeight)for(let page=1;page*first.viewportHeight<extent&&page<=80;page++){const y=topY+page*first.viewportHeight*scale;shape('line',{x1:docX,y1:y,x2:docX+docW,y2:y,stroke:'#e2e6eb','stroke-dasharray':'3 5'});if(plotHeight/(extent/first.viewportHeight)>18)shape('text',{x:docX+8,y:y-6,fill:'#94a3b8','font-size':10},String(page));}
 const initialY=topY+evidence.initialHeight*scale,finalY=topY+evidence.finalHeight*scale;
 shape('rect',{x:docX+5,y:topY+5,width:docW-10,height:Math.max(0,evidence.initialHeight*scale-5),fill:'none',stroke:'#c27a22','stroke-dasharray':'6 4','stroke-width':2,'data-initial-height':evidence.initialHeight});
 shape('line',{x1:15,y1:topY,x2:15,y2:initialY,stroke:'#c27a22','stroke-width':2});for(const y of [topY,initialY])shape('line',{x1:10,y1:y,x2:23,y2:y,stroke:'#c27a22','stroke-width':2});shape('text',{x:28,y:initialY/2+topY/2-8,fill:'#a96213','font-size':12},'Initial');shape('text',{x:28,y:initialY/2+topY/2+10,fill:'#a96213','font-size':12},px(evidence.initialHeight));
 shape('line',{x1:docX+docW+24,y1:topY,x2:docX+docW+24,y2:finalY,stroke:'#446b97','stroke-width':2});for(const y of [topY,finalY])shape('line',{x1:docX+docW+17,y1:y,x2:docX+docW+31,y2:y,stroke:'#446b97','stroke-width':2});shape('text',{x:docX+docW+36,y:finalY/2+topY/2-8,fill:'#446b97','font-size':12},'Final');shape('text',{x:docX+docW+36,y:finalY/2+topY/2+10,fill:'#446b97','font-size':12},px(evidence.finalHeight));
 const overlays=frames.map((frame,index)=>{const rect=shape('rect',{x:docX+docW*frame.x/width,y:topY+frame.y*scale,width:Math.min(docW,docW*frame.viewportWidth/width),height:frame.viewportHeight*scale,fill:'#7c3aed',stroke:'#7c3aed','fill-opacity':.035,'stroke-opacity':.2,'stroke-width':1,'data-frame':index,'data-scroll-y':frame.y,'data-viewport-height':frame.viewportHeight});const title=document.createElementNS(svg.namespaceURI,'title');title.textContent=`${frame.phase} · y=${frame.y} · ${frame.viewportWidth} × ${frame.viewportHeight}`;rect.append(title);return rect});
 const selectedLabel=shape('text',{x:docX,y:plotHeight+topY+28,fill:'#6d28d9','font-size':12});
 const legend=el('div',undefined,'legend');legend.append(el('span','Initial height','initial'),el('span','Final document'),el('span','Captured viewport','viewport'));map.append(legend);
 const heading=el('h2'),image=el('img') as HTMLImageElement;image.hidden=true;image.alt='Captured scrolling frame';const details=el('dl',undefined,'frame-info'),preview=el('div',undefined,'frame-preview'),measurement=el('div',undefined,'measurement-preview');preview.append(measurement,image);detail.append(heading,preview,details);
 const controls=el('div',undefined,'controls'),back=el('button','↑') as HTMLButtonElement,next=el('button','↓') as HTMLButtonElement,slider=document.createElement('input');back.setAttribute('aria-label','Previous captured position');next.setAttribute('aria-label','Next captured position');slider.type='range';slider.min='0';slider.max=String(Math.max(0,frames.length-1));slider.value='0';slider.setAttribute('aria-label','Captured scroll position');slider.setAttribute('aria-orientation','vertical');controls.append(back,slider,next);map.prepend(controls);
 const tablePanel=el('section',undefined,'panel'),list=el('div',undefined,'frame-list'),table=el('table'),thead=el('thead'),tr=el('tr');for(const title of ['Position','Time','Scroll X / Y','Viewport','Document','Expanded'])tr.append(el('th',title));thead.append(tr);const tbody=el('tbody');table.append(thead,tbody);list.append(table);tablePanel.append(el('h2','Captured positions'),list);if(frames.length)content.append(tablePanel);
 let selected=0;const rows:HTMLElement[]=[];
 const choose=(index:number)=>{selected=Math.max(0,Math.min(frames.length-1,index));const frame=frames[selected];if(!frame){heading.textContent='Page screenshot';controls.hidden=true;return}heading.textContent=frame.phase+(frame.step!=null?' '+frame.step:'');slider.value=String(selected);back.disabled=selected===0;next.disabled=selected===frames.length-1;details.replaceChildren();for(const[label,value]of [['Scroll position',`${px(frame.x)} / ${px(frame.y)}`],['Viewport',`${num(frame.viewportWidth)} × ${num(frame.viewportHeight)}`],['Document',frame.height?`${num(frame.width)} × ${num(frame.height)}`:'—'],['Time',`${frame.elapsedMs>=0?'+':''}${num(frame.elapsedMs)} ms`],['Source',frame.source||'Scroll measurement'],['Details expanded',frame.expanded??'—']])if(value!=null){const item=el('div');item.append(el('dt',label),el('dd',value));details.append(item)}const url=options.resourceURL(frame.image);image.hidden=!url;measurement.hidden=!!url;measurement.replaceChildren(el('strong',`${num(frame.viewportWidth)} × ${num(frame.viewportHeight)}`),el('span',`Y ${px(frame.y)}`));slider.setAttribute('aria-valuetext',`${frame.phase}${frame.step!=null?' '+frame.step:''}; Y ${px(frame.y)}`);if(url)image.src=url;else image.removeAttribute('src');overlays.forEach((rect,i)=>{rect.setAttribute('fill-opacity',i===selected?'.15':'.025');rect.setAttribute('stroke-opacity',i===selected?'1':'.2');rect.setAttribute('stroke-width',i===selected?'2.5':'1')});const active=overlays[selected];if(active)svg.append(active);svg.append(selectedLabel);selectedLabel.textContent=`${frame.phase}${frame.step!=null?' '+frame.step:''} · y ${px(frame.y)} → ${px(frame.y+frame.viewportHeight)}`;rows.forEach((row,i)=>row.setAttribute('aria-selected',String(i===selected)));};
 frames.forEach((frame,index)=>{const row=el('tr');row.tabIndex=0;for(const value of [frame.phase+(frame.step!=null?' '+frame.step:''),`${frame.elapsedMs>=0?'+':''}${num(frame.elapsedMs)} ms`,`${num(frame.x)} / ${num(frame.y)}`,`${num(frame.viewportWidth)} × ${num(frame.viewportHeight)}`,frame.height?`${num(frame.width)} × ${num(frame.height)}`:'—',frame.expanded??'—'])row.append(el('td',value));row.onclick=()=>choose(index);row.onkeydown=event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();choose(index)}};tbody.append(row);rows.push(row)});back.onclick=()=>choose(selected-1);next.onclick=()=>choose(selected+1);slider.oninput=()=>choose(Number(slider.value));choose(0);
 if(screenshots.length){const section=el('section');section.style.marginTop='20px';section.append(el('h2','Page screenshot'));const tiles=el('div');tiles.style.cssText=`position:relative;width:100%;aspect-ratio:${screenshots[0]!.fullWidth}/${screenshots[0]!.fullHeight};overflow:hidden;border:1px solid var(--line);border-radius:6px`;for(const tile of screenshots){const url=options.resourceURL(tile.url);if(!url)continue;const img=el('img') as HTMLImageElement;img.src=url;img.alt='Captured page screenshot';img.loading='lazy';img.style.cssText=`position:absolute;left:${100*tile.x/tile.fullWidth}%;top:${100*tile.y/tile.fullHeight}%;width:${100*tile.width/tile.fullWidth}%;height:${100*tile.height/tile.fullHeight}%;max-height:none;object-fit:fill;border:0;border-radius:0`;tiles.append(img)}const viewport=el('div');viewport.style.cssText='max-height:340px;overflow:auto;border-radius:6px';viewport.append(tiles);section.append(viewport);detail.append(section)}
}
